version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/Geek-in-the-Punk
hooks:
  AfterInstall:
    - location: scripts/set_owner.sh
      timeout: 5
      runas: root
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: ec2-user
    - location: scripts/build.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 10
      runas: root
  ValidateService: 
    - location: scripts/validate_nginx.sh
      timeout: 10
      runas: root