version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/Geek-in-the-Punk
hooks:
  AfterInstall:
    - location: /var/www/Geek-in-the-Punk/scripts/set_owner
      timeout: 5
      runas: root
    - location: /var/www/Geek-in-the-Punk/scripts/install_dependencies
      timeout: 120
      runas: ec2-user
    - location: /var/www/Geek-in-the-Punk/scripts/build
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: /var/www/Geek-in-the-Punk/scripts/restart_server
      timeout: 10
      runas: root
  ValidateService: 
    - location: /var/www/Geek-in-the-Punk/scripts/validate_nginx
      timeout: 10
      runas: root